# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/yingzong/vOld/project_1/project_1.cache/wt [current_project]
set_property parent.project_path D:/yingzong/vOld/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_mem D:/yingzong/vOld/project_1/code/code/inst_rom.data
read_verilog -library xil_defaultlib {
  D:/yingzong/vOld/project_1/code/code/defines.v
  D:/yingzong/vOld/project_1/code/code/regfile.v
  D:/yingzong/vOld/project_1/code/code/pc_reg.v
  D:/yingzong/vOld/project_1/code/code/mem_wb.v
  D:/yingzong/vOld/project_1/code/code/mem.v
  D:/yingzong/vOld/project_1/code/code/if_id.v
  D:/yingzong/vOld/project_1/code/code/id_ex.v
  D:/yingzong/vOld/project_1/code/code/id.v
  D:/yingzong/vOld/project_1/code/code/hilo_reg.v
  D:/yingzong/vOld/project_1/code/code/ex_mem.v
  D:/yingzong/vOld/project_1/code/code/ex.v
  D:/yingzong/vOld/project_1/code/code/ctrl.v
  D:/yingzong/vOld/project_1/code/code/div.v
  D:/yingzong/vOld/project_1/code/code/openmips.v
  D:/yingzong/vOld/project_1/code/code/inst_rom.v
  D:/yingzong/vOld/project_1/code/code/openmips_min_sopc.v
  D:/yingzong/vOld/project_1/code/code/openmips_min_sopc_tb.v
}
synth_design -top openmips_min_sopc_tb -part xc7vx485tffg1157-1
write_checkpoint -noxdef openmips_min_sopc_tb.dcp
catch { report_utilization -file openmips_min_sopc_tb_utilization_synth.rpt -pb openmips_min_sopc_tb_utilization_synth.pb }
